language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
  - php: nightly

before_script:
  # Make sure the locales used in the tests are installed
  - sudo locale-gen en_GB
  - sudo locale-gen en_GB.utf8
  - sudo locale-gen fr_FR
  - sudo locale-gen fr_FR@euro
  - sudo locale-gen fr_FR.utf8

script:
  - composer tests

install:
  - travis_retry composer install --no-interaction --prefer-source
